import { useEffect, useState } from "react";
import { Box, Typography, CircularProgress } from "@mui/material";
import { DownloadOutlined as DownloadIcon } from "@mui/icons-material";
import DashboardLayout from "../../layouts/DashboardLayout";
import { COLORS } from "../../constants/colors";
import { exportAPI } from "../../services/api";

/*
 * Read-only exports for the User role. SRS §10.2 grants "View exports
 * (read-only): Yes" and "Generate exports: No", so this lists what has been
 * issued and lets it be downloaded — there is deliberately no generate control.
 */
interface ExportRow {
  _id: string;
  date: string;
  type: string;
  week: string;
  generatedBy: string;
  status: string;
  fileName?: string;
}

const formatDate = (value: string) => {
  if (!value) return "-";
  return new Date(value).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const UserExports = () => {
  const [exports, setExports] = useState<ExportRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  useEffect(() => {
    const fetchExports = async () => {
      try {
        const res = await exportAPI.getHistory();
        if (res.success) setExports(res.exports || []);
      } catch (error) {
        console.error("Failed to fetch exports:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchExports();
  }, []);

  const handleDownload = async (id: string, fileName?: string) => {
    setDownloadingId(id);
    try {
      const response = await exportAPI.download(id);
      const blob = new Blob([response.data], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = fileName || "export.xlsx";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading export:", error);
    } finally {
      setDownloadingId(null);
    }
  };

  const columns = "1.2fr 1.6fr 0.8fr 1.4fr 0.9fr 0.7fr";

  return (
    <DashboardLayout title="Exports" subtitle="View and download issued outputs">
      <Box
        sx={{
          bgcolor: COLORS.bgSecondary,
          border: `1px solid ${COLORS.border}`,
          borderRadius: "12px",
          overflow: "hidden",
        }}
      >
        <Box sx={{ p: 3, borderBottom: `1px solid ${COLORS.border}` }}>
          <Typography
            sx={{
              color: COLORS.textPrimary,
              fontSize: "16px",
              fontWeight: 600,
            }}
          >
            Export History
          </Typography>
          <Typography sx={{ color: COLORS.textMuted, fontSize: "13px" }}>
            Weekly Work Plans and Planner To-Do lists issued by the team
          </Typography>
        </Box>

        <Box sx={{ overflowX: "auto" }}>
          <Box sx={{ minWidth: 820 }}>
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: columns,
                gap: 2,
                px: 3,
                py: 1.5,
                borderBottom: `1px solid ${COLORS.border}`,
              }}
            >
              {["DATE", "TYPE", "WEEK", "GENERATED BY", "STATUS", "FILE"].map(
                (header) => (
                  <Typography
                    key={header}
                    sx={{
                      color: COLORS.textMuted,
                      fontSize: "11px",
                      fontWeight: 600,
                      letterSpacing: "0.5px",
                    }}
                  >
                    {header}
                  </Typography>
                ),
              )}
            </Box>

            {loading ? (
              <Box sx={{ py: 6, textAlign: "center" }}>
                <CircularProgress size={24} sx={{ color: COLORS.blue }} />
              </Box>
            ) : exports.length === 0 ? (
              <Box sx={{ py: 6, textAlign: "center" }}>
                <Typography
                  sx={{ color: COLORS.textMuted, fontSize: "14px" }}
                >
                  No exports have been issued yet
                </Typography>
              </Box>
            ) : (
              exports.map((row, index) => (
                <Box
                  key={row._id}
                  sx={{
                    display: "grid",
                    gridTemplateColumns: columns,
                    gap: 2,
                    px: 3,
                    py: 2,
                    alignItems: "center",
                    borderBottom:
                      index < exports.length - 1
                        ? `1px solid ${COLORS.border}`
                        : "none",
                  }}
                >
                  <Typography
                    sx={{ color: COLORS.textSecondary, fontSize: "13px" }}
                  >
                    {formatDate(row.date)}
                  </Typography>
                  <Typography
                    sx={{ color: COLORS.textPrimary, fontSize: "13px" }}
                  >
                    {row.type}
                  </Typography>
                  <Typography
                    sx={{ color: COLORS.textSecondary, fontSize: "13px" }}
                  >
                    {row.week || "-"}
                  </Typography>
                  <Typography
                    sx={{ color: COLORS.textSecondary, fontSize: "13px" }}
                  >
                    {row.generatedBy}
                  </Typography>
                  <Box>
                    <Box
                      component="span"
                      sx={{
                        bgcolor:
                          row.status === "Complete"
                            ? `${COLORS.green}20`
                            : `${COLORS.amber}20`,
                        color:
                          row.status === "Complete"
                            ? COLORS.green
                            : COLORS.amber,
                        px: 1.5,
                        py: 0.5,
                        borderRadius: "5px",
                        fontSize: "12px",
                        fontWeight: 500,
                      }}
                    >
                      {row.status}
                    </Box>
                  </Box>
                  <Box
                    onClick={() =>
                      downloadingId ? null : handleDownload(row._id, row.fileName)
                    }
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: 0.5,
                      color: COLORS.blue,
                      cursor: downloadingId ? "not-allowed" : "pointer",
                      opacity: downloadingId === row._id ? 0.5 : 1,
                      fontSize: "13px",
                      "&:hover": { textDecoration: "underline" },
                    }}
                  >
                    <DownloadIcon sx={{ fontSize: 16 }} />
                    {downloadingId === row._id ? "..." : "Download"}
                  </Box>
                </Box>
              ))
            )}
          </Box>
        </Box>
      </Box>
    </DashboardLayout>
  );
};

export default UserExports;
