import PDFDocument from "pdfkit";
import fs from "fs";

const BLACK = "#000000";
const GRAY = "#666666";
const LIGHT_GRAY = "#E5E5E5";
const WHITE = "#FFFFFF";
const HEADER_BG = "#F0F0F0";

// Programme window: 31-Jul-2026 .. 20-Aug-2026 (upload with device date = 31 Jul 2026)
// Activity IDs ACT-501 .. ACT-510 (distinct from cycle 4's ACT-001 series).
// Zones relative to the 6-week lookahead anchored on 31-Jul-2026:
//   Weeks 1-2 : 31-Jul .. 13-Aug
//   Weeks 3-4 : 14-Aug .. 27-Aug  (programme ends 20-Aug, so partially covered)
//   Weeks 5-6 : 28-Aug .. 10-Sep  (no activities - programme ends first)
// Working days only (Mon-Fri); 31-Jul-2026 is a Friday.
const activities = [
  {
    id: "ACT-501",
    name: "Site Establishment & Welfare",
    duration: "2d",
    start: "31-Jul-26",
    finish: "03-Aug-26",
    zone: "Weeks 1-2",
  },
  {
    id: "ACT-502",
    name: "Utility Diversion Survey",
    duration: "4d",
    start: "03-Aug-26",
    finish: "06-Aug-26",
    zone: "Weeks 1-2",
  },
  {
    id: "ACT-503",
    name: "Topsoil Strip and Stockpile",
    duration: "5d",
    start: "05-Aug-26",
    finish: "11-Aug-26",
    zone: "Weeks 1-2",
  },
  {
    id: "ACT-504",
    name: "Haul Road Construction",
    duration: "3d",
    start: "10-Aug-26",
    finish: "12-Aug-26",
    zone: "Weeks 1-2",
  },
  {
    id: "ACT-505",
    name: "Attenuation Tank Excavation",
    duration: "4d",
    start: "10-Aug-26",
    finish: "13-Aug-26",
    zone: "Weeks 1-2",
  },

  {
    id: "ACT-506",
    name: "Blinding and Formwork",
    duration: "3d",
    start: "14-Aug-26",
    finish: "18-Aug-26",
    zone: "Weeks 3-4",
  },
  {
    id: "ACT-507",
    name: "Retaining Wall Bases",
    duration: "5d",
    start: "14-Aug-26",
    finish: "20-Aug-26",
    zone: "Weeks 3-4",
  },
  {
    id: "ACT-508",
    name: "Service Ducting Installation",
    duration: "4d",
    start: "17-Aug-26",
    finish: "20-Aug-26",
    zone: "Weeks 3-4",
  },
  {
    id: "ACT-509",
    name: "Kerb and Edging Works",
    duration: "3d",
    start: "18-Aug-26",
    finish: "20-Aug-26",
    zone: "Weeks 3-4",
  },
  {
    id: "ACT-510",
    name: "Precast Panel Delivery and Set",
    duration: "2d",
    start: "19-Aug-26",
    finish: "20-Aug-26",
    zone: "Weeks 3-4",
  },
];

const doc = new PDFDocument({
  size: "A3",
  layout: "landscape",
  margins: { top: 15, bottom: 15, left: 15, right: 15 },
});

const outputPath = "/Users/apple/Downloads/m5_test_cycle_5.pdf";
doc.pipe(fs.createWriteStream(outputPath));

const pageWidth = doc.page.width - 30;

const COL_ID_X = 15;
const COL_ID_WIDTH = 85;
const COL_NAME_X = 100;
const COL_NAME_WIDTH = 320;
const COL_DURATION_X = 420;
const COL_DURATION_WIDTH = 60;
const COL_START_X = 480;
const COL_START_WIDTH = 75;
const COL_FINISH_X = 555;
const COL_FINISH_WIDTH = 75;
const TABLE_END_X = 630;

let y = 15;

doc.fontSize(12).fillColor(BLACK);
doc.text("M5 Test Cycle 5 Construction Programme / 2026", 15, y);
doc.fontSize(8).fillColor(GRAY);
doc.text("31/07/2026", pageWidth - 60, y);

y += 35;

doc.rect(COL_ID_X, y, TABLE_END_X - COL_ID_X, 22).fill(HEADER_BG);

doc.fontSize(8).fillColor(BLACK).font("Helvetica-Bold");
doc.text("Activity ID", COL_ID_X + 3, y + 6);
doc.text("Activity Name", COL_NAME_X + 3, y + 6);
doc.text("Duration", COL_DURATION_X + 3, y + 6);
doc.text("Start", COL_START_X + 3, y + 6);
doc.text("Finish", COL_FINISH_X + 3, y + 6);

doc.strokeColor(GRAY).lineWidth(0.5);
[COL_NAME_X, COL_DURATION_X, COL_START_X, COL_FINISH_X, TABLE_END_X].forEach(
  (x) => {
    doc
      .moveTo(x, y)
      .lineTo(x, y + 22)
      .stroke();
  },
);

y += 22;

const rowHeight = 20;
doc.font("Helvetica");

activities.forEach((activity, index) => {
  const rowY = y + index * rowHeight;

  doc
    .rect(COL_ID_X, rowY, TABLE_END_X - COL_ID_X, rowHeight)
    .fill(index % 2 === 0 ? "#FAFAFA" : WHITE);

  doc.strokeColor(LIGHT_GRAY).lineWidth(0.3);
  doc.rect(COL_ID_X, rowY, TABLE_END_X - COL_ID_X, rowHeight).stroke();

  [COL_NAME_X, COL_DURATION_X, COL_START_X, COL_FINISH_X].forEach((x) => {
    doc
      .moveTo(x, rowY)
      .lineTo(x, rowY + rowHeight)
      .stroke();
  });

  doc.fontSize(7).fillColor(BLACK).font("Helvetica");
  doc.text(activity.id, COL_ID_X + 3, rowY + 6, { width: COL_ID_WIDTH - 6 });
  doc.text(activity.name, COL_NAME_X + 3, rowY + 6, {
    width: COL_NAME_WIDTH - 6,
  });
  doc.text(activity.duration, COL_DURATION_X + 3, rowY + 6, {
    width: COL_DURATION_WIDTH - 6,
    align: "center",
  });
  doc.text(activity.start, COL_START_X + 3, rowY + 6, {
    width: COL_START_WIDTH - 6,
    align: "center",
  });
  doc.text(activity.finish, COL_FINISH_X + 3, rowY + 6, {
    width: COL_FINISH_WIDTH - 6,
    align: "center",
  });
});

const footerY = y + activities.length * rowHeight + 20;
doc.fontSize(6).fillColor(GRAY);
doc.text(
  "Generated by PlanSure | programme window 31 Jul 2026 - 20 Aug 2026 | upload with device date = 31 Jul 2026",
  15,
  footerY,
);

doc.end();
