import PDFDocument from "pdfkit";
import fs from "fs";

const doc = new PDFDocument({
  size: "A3",
  layout: "landscape",
  margins: { top: 30, bottom: 30, left: 30, right: 30 },
});

const outputPath = "./test-programme.pdf";
doc.pipe(fs.createWriteStream(outputPath));

const BLACK = "#000000";
const GRAY = "#666666";
const WHITE = "#FFFFFF";

const pageWidth = doc.page.width - 60;

const COL_ID_X = 30;
const COL_NAME_X = 130;
const COL_DURATION_X = 480;
const COL_START_X = 550;
const COL_FINISH_X = 630;

const activities = [
  {
    id: "WP-FW-001",
    name: "Foundation Works Zone A",
    duration: "45",
    start: "01-Jan-24",
    finish: "14-Feb-24",
  },
  {
    id: "WP-ST-002",
    name: "Steel Structure Erection Main Hall",
    duration: "60",
    start: "15-Feb-24",
    finish: "15-Apr-24",
  },
  {
    id: "WP-ME-003",
    name: "MEP Rough-In Level 1",
    duration: "30",
    start: "16-Apr-24",
    finish: "15-May-24",
  },
  {
    id: "MS-SC-001",
    name: "Milestone Structural Completion",
    duration: "0",
    start: "15-May-24",
    finish: "15-May-24",
  },
  {
    id: "WP-FA-004",
    name: "Facade Installation East Wing",
    duration: "45",
    start: "16-May-24",
    finish: "30-Jun-24",
  },
  {
    id: "WP-IF-005",
    name: "Interior Fit-Out Departures Lounge",
    duration: "60",
    start: "01-Jul-24",
    finish: "30-Aug-24",
  },
  {
    id: "WP-BM-006",
    name: "BMS Integration and Testing",
    duration: "30",
    start: "01-Sep-24",
    finish: "30-Sep-24",
  },
  {
    id: "MS-SH-002",
    name: "Milestone Systems Handover",
    duration: "0",
    start: "01-Oct-24",
    finish: "01-Oct-24",
  },
  {
    id: "WP-CM-007",
    name: "Final Commissioning and Snagging",
    duration: "90",
    start: "01-Oct-24",
    finish: "31-Dec-24",
  },
  {
    id: "WP-QA-008",
    name: "Quality Assurance Review",
    duration: "14",
    start: "15-Dec-24",
    finish: "31-Dec-24",
  },
];

let y = 30;
doc.fontSize(14).fillColor(BLACK).text("Terminal 2 Expansion Programme", 30, y);
y += 30;

doc.fontSize(9).fillColor(GRAY);
doc.text("Activity ID", COL_ID_X, y);
doc.text("Activity Name", COL_NAME_X, y);
doc.text("Duration", COL_DURATION_X, y);
doc.text("Start", COL_START_X, y);
doc.text("Finish", COL_FINISH_X, y);

y += 20;

doc.strokeColor(GRAY).lineWidth(0.5);
doc
  .moveTo(30, y - 5)
  .lineTo(pageWidth, y - 5)
  .stroke();

doc.fontSize(8).fillColor(BLACK);
const rowHeight = 18;

activities.forEach((activity, index) => {
  const rowY = y + index * rowHeight;

  doc.text(activity.id, COL_ID_X, rowY);

  doc.text(activity.name, COL_NAME_X, rowY, { width: 340 });

  doc.text(activity.duration, COL_DURATION_X, rowY);

  doc.text(activity.start, COL_START_X, rowY);

  doc.text(activity.finish, COL_FINISH_X, rowY);
});

y = y + activities.length * rowHeight + 30;
doc.fontSize(7).fillColor(GRAY);
doc.text("Generated by PlanSure", 30, y);

doc.end();
